# Travis configuration for PalMA

# TODO:
# Errors from docs/dist/pre-commit.sh are currently ignored
# because there are too many coding violations in PHP code.

sudo: false

language: php

# php-codesniffer is used for the PSR-2 conformance test.
addons:
  apt:
    packages:
      - php-codesniffer
      - libperl-critic-perl
      - shellcheck

script:
      - docs/dist/pre-commit.sh . || echo Ignored errors
      - docs/dist/pre-push.sh
