# Travis configuration for PalMA

sudo: false

language: php

# php-codesniffer is used for the PSR-2 conformance test.
addons:
  apt:
    packages:
      - php-codesniffer

script:
      - perl docs/dist/check-signed-off.pl
